mode = "light"

accent = "#0057B8"
# This refers to "selection background"
selection = "#BCD0E4"
# This refers to "muted text"
muted = "#8D99A5"

background = "#E2E6EA"
dark_background = "#D3D9E0"
darker_background = "#C4CCD5"
lighter_background = "#F0F2F4"

# For herdr, "foreground" should be legible on "muted"
# For yazi, "foreground" should be legible on "blue"
foreground = "#1F2933"
dark_foreground = "#111820"
light_foreground = "#3D4854"
bright_foreground = "#6B7580"

red = "#B54747"
yellow = "#8B6815"
orange = "#A65728"
green = "#3F7651"
cyan = "#32777A"
# For yazi, "blue" should be legible on "background"
blue = "#5B82A3"
magenta = "#7C5C8E"
brown = "#755846"

bright_red = "#C43F4D"
bright_yellow = "#9B7411"
bright_green = "#2F8050"
bright_cyan = "#188087"
bright_blue = "#3976AA"
bright_magenta = "#8755A0"
