foreground #DCE3EC
background #1A2332
selection_foreground #F5F7FA
selection_background #34445A

cursor #F5F7FA
cursor_text_color #1A2332

active_border_color #0052CC
active_tab_background #0052CC

color0 #1A2332
color1 #D16D75
color2 #6FA27C
color3 #C9A65A
color4 #6F9FD1
color5 #9A82B4
color6 #68A6AD
color7 #DCE3EC
color8 #657386
color9 #E2878D
color10 #89B593
color11 #DFC477
color12 #8AB4DE
color13 #B29AC8
color14 #82BEC4
color15 #F5F7FA
